name: <h1 style="font-size:70%">ENCYCLOPEDIA</h1>
description: The encyclopedia page hosted by <b>zuox.in</b>
#markdown: redcarpet
highlighter: true
#disqus-id: 
#email: 
twitter: xiaoxinxinzuo
github: siuyanyan